### ISSUE TITLE
Game Support: Halo 4

### ISSUE THREAD

**Issue by emoose** [emoose/xenia#5]
Right now I'm not able to load into any H4 map, seems to guest crash at the menu, does anyone know a fix for that?

If I can at least load into a map and move camera with controller hopefully I can add support for it to Halo3Game class, assuming H4 uses similar things to handle the camera like the other Halo games (quick look in IDA seems it's similar, but no idea since I haven't been able to start it...)

**Comment by Nighterlev** [comment]
If you're trying to access Halo 4's DLC maps without patching the default.xex, Halo 4 will exit to the main menu.  It's not really "crashing", but it's refusing to load the map due to a unpatched default.xex, then reverting back to the main menu.  This same behavior happens on a Xbox 360, and Xenia.  

You can load all the "War games" aka the base Halo 4 maps just like (like Adrift, Abandon, Complex, Haven, etc.) just fine, but without a patched xex, it won't allow you to load any of the dlc maps.  

Did experience a weird anomaly where my patched xex of Halo 4 was causing Xenia to freeze (sometimes the dlc maps would never show up) but restarting my computer seemed to of fixed it.  The unpatched one didn't have such issues, and the feb. 1st build worked fine either.  Restarted it as a last resort and it seemed to of fixed whatever the problem was initially.  

That's my best guesses really. After the restart, on a patched xex of Halo 4, the mp maps are working fine for me.

**Comment by emoose** [comment]
@Nighterlev ah was hoping you'd see this, right now I can't even load into any map, let alone DLC, just guest crashes a few seconds after "press start" appears...
I seem to remember something about needing bik files removed, is something like that still needed?

Maybe the copy of H4 I'm using is just a bad dump or something, I'll try seeing if I can get a different one.

**Comment by Nighterlev** [comment]
Not trying to reopen this or anything, but the bik files being removed isn't needed anymore.  Around Nov. 2020 Rick added a new kernel function which fixed cut scenes causing Halo 4 to crash, Halo 3 crashes, reach and ODST crashes.  Even Halo Wars 1 goes in-game now.  
That kernel function was kernel-KeSetCurrentStackPointers.  I was actually experiencing those same crashes until I restarted my computer which "fixed" the issue for some odd reason, can't really figure out why yours was crashing at all.
